# generated by datamodel-codegen:
#   filename:  sprotty/actions/action.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Action(BaseModel):
    kind: str
    requestId: str | None = None
