# generated by datamodel-codegen:
#   filename:  sprotty/actions/action.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from pydantic import BaseModel


class Action(BaseModel):
    kind: str
    requestId: str | None = None
