# generated by datamodel-codegen:
#   filename:  sprotty/actions/allSelected.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from .action import Action


class Kind(Enum):
    allSelected = 'allSelected'


class AllSelected(Action):
    kind: Kind | None = 'allSelected'
    select: bool
