# generated by datamodel-codegen:
#   filename:  sprotty/actions/elementSelected.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from enum import Enum

from .action import Action


class Kind(Enum):
    elementSelected = 'elementSelected'


class ElementSelected(Action):
    kind: Kind | None = 'elementSelected'
    selectedElementsIDs: list[str]
    deselectedElementsIDs: list[str]
    preventOpenSelection: bool
