# generated by datamodel-codegen:
#   filename:  sprotty/actions/fit.json
#   timestamp: 2026-03-02T11:21:50+00:00

from __future__ import annotations

from enum import Enum

from .action import Action


class Kind(Enum):
    fit = 'fit'


class Fit(Action):
    kind: Kind | None = 'fit'
    elementIds: list[str]
    maxZoom: float
    animate: bool
