# generated by datamodel-codegen:
#   filename:  sprotty/actions/requestBounds.json
#   timestamp: 2026-03-02T15:38:45+00:00

from __future__ import annotations

from enum import Enum

from ...klighd import SKGraphSchema
from .action import Action


class Kind(Enum):
    requestBounds = 'requestBounds'


class RequestBounds(Action):
    kind: Kind | None = 'requestBounds'
    newRoot: SKGraphSchema.SKGraph
