# generated by datamodel-codegen:
#   filename:  sprotty/actions/requestModel.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from .action import Action


class Kind(Enum):
    requestModel = 'requestModel'


class DiagramType(Enum):
    keith_diagram = 'keith-diagram'


class Options(BaseModel):
    needsClientLayout: bool | None = None
    needsServerLayout: bool | None = None
    sourceUri: str | None = None
    diagramType: DiagramType | None = None


class RequestModel(Action):
    kind: Kind | None = 'requestModel'
    options: Options
    requestId: str
