# generated by datamodel-codegen:
#   filename:  sprotty/actions/setModel.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from ...klighd import SKGraphSchema
from .action import Action


class Kind(Enum):
    setModel = 'setModel'


class SetModel(Action):
    kind: Kind | None = 'setModel'
    newRoot: SKGraphSchema.SKGraph
