# generated by datamodel-codegen:
#   filename:  sprotty/actions/updateModel.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from ...klighd import SKGraphSchema
from .action import Action


class Kind(Enum):
    updateModel = 'updateModel'


class UpdateModel(Action):
    kind: Kind | None = 'updateModel'
    newRoot: SKGraphSchema.SKGraph
