# generated by datamodel-codegen:
#   filename:  lsp/generalSendMessage.json
#   timestamp: 2026-03-02T11:21:50+00:00

from __future__ import annotations

from enum import Enum

from .requestMessage import RequestMessage


class Method(Enum):
    general_sendMessage = 'general/sendMessage'


class GeneralSendmessage(RequestMessage):
    method: Method | None = 'general/sendMessage'
    params: list[str]
