# generated by datamodel-codegen:
#   filename:  lsp/initialize.json
#   timestamp: 2026-03-02T15:38:45+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel

from .requestMessage import RequestMessage


class Method(Enum):
    initialize = 'initialize'


class ClientInfo(BaseModel):
    name: str | None = None


class ClientDiagramOptions(BaseModel):
    preference: dict[str, Any] | None = None
    render: dict[str, Any] | None = None
    synthesis: dict[str, Any] | None = None


class InitializationOptions(BaseModel):
    clientDiagramOptions: ClientDiagramOptions | None = None


class Params(BaseModel):
    processId: Any | None = None
    workspaceFolders: Any | None = None
    rootUri: Any | None = None
    clientInfo: ClientInfo | None = None
    capabilities: dict[str, Any] | None = None
    initializationOptions: InitializationOptions | None = None


class Initialize(RequestMessage):
    method: Method | None = 'initialize'
    params: Params
