# generated by datamodel-codegen:
#   filename:  lsp/message.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Jsonrpc(Enum):
    field_2_0 = '2.0'


class Message(BaseModel):
    jsonrpc: Jsonrpc | None = '2.0'
