# generated by datamodel-codegen:
#   filename:  lsp/range.json
#   timestamp: 2026-03-02T15:38:45+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, RootModel


class EditorPosition(BaseModel):
    line: int
    character: int


class EditorPositionModel(RootModel[Any]):
    root: Any


class Range(BaseModel):
    start: EditorPosition
    end: EditorPosition
