# generated by datamodel-codegen:
#   filename:  lsp/requestMessage.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from .message import Message


class Method(Enum):
    requestMessage = 'requestMessage'


class RequestMessage(Message):
    id: float | str | None = None
    method: Method | None = 'requestMessage'
    params: list[Any] | dict[str, Any] | None = None
