# generated by datamodel-codegen:
#   filename:  lsp/responseMessage.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from typing import Any

from .message import Message


class ResponseMessage(Message):
    id: float | str | None
    result: Any | None = None
    error: Any | None = None
