# generated by datamodel-codegen:
#   filename:  lsp/textDocumentDocumentHighlight.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from . import range
from .requestMessage import RequestMessage


class Method(Enum):
    textDocument_documentHighlight = 'textDocument/documentHighlight'


class TextDocument(BaseModel):
    uri: str | None = None


class Params(BaseModel):
    textDocument: TextDocument | None = None
    position: range.EditorPositionModel | None = None


class TextdocumentDocumenthighlight(RequestMessage):
    method: Method | None = 'textDocument/documentHighlight'
    params: Params
