# generated by datamodel-codegen:
#   filename:  klighd/actions/checkImages.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    checkImages = 'checkImages'


class Image(BaseModel):
    bundleName: str
    imagePath: str


class CheckImages(Action):
    kind: Kind | None = 'checkImages'
    images: list[Image]
