# generated by datamodel-codegen:
#   filename:  klighd/actions/checkedImages.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    checkedImages = 'checkedImages'


class NotCachedImage(BaseModel):
    k: str
    v: str


class CheckedImages(Action):
    kind: Kind | None = 'checkedImages'
    notCached: list[NotCachedImage]
    responseId: str
