# generated by datamodel-codegen:
#   filename:  klighd/actions/checkImages.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    checkImages = 'checkImages'


class Image(BaseModel):
    bundleName: str
    imagePath: str


class CheckImages(Action):
    kind: Kind | None = 'checkImages'
    images: list[Image]
