# generated by datamodel-codegen:
#   filename:  klighd/actions/performAction.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action


class Kind(Enum):
    performAction = 'performAction'


class PerformAction(Action):
    kind: Kind | None = 'performAction'
    actionId: str
    kGraphElementId: str
    kRenderingId: str
    revision: float
