# generated by datamodel-codegen:
#   filename:  klighd/actions/refreshDiagram.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    refreshDiagram = 'refreshDiagram'


class Options(BaseModel):
    needsClientLayout: bool | None = None
    needsServerLayout: bool | None = None


class RefreshDiagram(Action):
    kind: Kind | None = 'refreshDiagram'
    options: Options | None = None
