# generated by datamodel-codegen:
#   filename:  klighd/actions/requestDiagramPiece.json
#   timestamp: 2026-03-02T15:38:45+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action


class Kind(Enum):
    requestDiagramPiece = 'requestDiagramPiece'


class RequestDiagramPiece(Action):
    kind: Kind | None = 'requestDiagramPiece'
    modelElementId: str
