# generated by datamodel-codegen:
#   filename:  klighd/actions/setDiagramPiece.json
#   timestamp: 2026-03-02T15:38:45+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action
from .. import SKGraphSchema


class Kind(Enum):
    setDiagramPiece = 'setDiagramPiece'


class SetDiagramPiece(Action):
    kind: Kind | None = 'setDiagramPiece'
    diagramPiece: SKGraphSchema.SKNode
