# generated by datamodel-codegen:
#   filename:  klighd/actions/setSynthesis.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action


class Kind(Enum):
    setSynthesis = 'setSynthesis'


class SetSynthesis(Action):
    kind: Kind | None = 'setSynthesis'
    id: str
