# generated by datamodel-codegen:
#   filename:  klighd/actions/setSyntheses.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...sprotty.actions.action import Action


class Kind(Enum):
    setSyntheses = 'setSyntheses'


class Synthesis(BaseModel):
    id: str
    displayName: str


class SetSyntheses(Action):
    kind: Kind | None = 'setSyntheses'
    syntheses: list[Synthesis]
