# generated by datamodel-codegen:
#   filename:  klighd/actions/setSynthesis.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from ...sprotty.actions.action import Action


class Kind(Enum):
    setSynthesis = 'setSynthesis'


class SetSynthesis(Action):
    kind: Kind | None = 'setSynthesis'
    id: str
