# generated by datamodel-codegen:
#   filename:  klighd/actions/updateOptions.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import Field

from ...sprotty.actions.action import Action
from .. import SynthesisOptionSchema


class Kind(Enum):
    updateOptions = 'updateOptions'


class UpdateOptions(Action):
    kind: Kind | None = 'updateOptions'
    valuedSynthesisOptions: list[SynthesisOptionSchema.ValuedSynthesisOption] | None = (
        Field(default_factory=list)
    )
    layoutOptions: list[Any] | None = []
    actions: list[Any] | None = []
    modelUri: str
