# generated by datamodel-codegen:
#   filename:  klighd/messages/diagramOptionsPerformAction.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...lsp.requestMessage import RequestMessage


class Method(Enum):
    keith_diagramOptions_performAction = 'keith/diagramOptions/performAction'


class Params(BaseModel):
    actionId: str
    uri: str


class KeithDiagramoptionsPerformaction(RequestMessage):
    method: Method | None = 'keith/diagramOptions/performAction'
    params: Params
