# generated by datamodel-codegen:
#   filename:  klighd/messages/diagramOptionsSetSynthesisOptions.json
#   timestamp: 2026-03-02T11:21:50+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ...lsp.requestMessage import RequestMessage
from .. import SynthesisOptionSchema


class Method(Enum):
    keith_diagramOptions_setSynthesisOptions = (
        'keith/diagramOptions/setSynthesisOptions'
    )


class Params(BaseModel):
    synthesisOptions: list[SynthesisOptionSchema.ValuedSynthesisOption]
    uri: str | None = None


class KeithDiagramoptionsSetsynthesisoptions(RequestMessage):
    method: Method | None = 'keith/diagramOptions/setSynthesisOptions'
    params: Params
