# generated by datamodel-codegen:
#   filename:  klighd/messages/diagramOptionsSetLayoutOptions.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel

from ...lsp.requestMessage import RequestMessage


class Method(Enum):
    keith_diagramOptions_setLayoutOptions = 'keith/diagramOptions/setLayoutOptions'


class LayoutOption(BaseModel):
    optionId: str
    value: Any


class Params(BaseModel):
    layoutOptions: list[LayoutOption]
    uri: str


class KeithDiagramoptionsSetlayoutoptions(RequestMessage):
    method: Method | None = 'keith/diagramOptions/setLayoutOptions'
    params: Params
