# generated by datamodel-codegen:
#   filename:  klighd/messages/preferencesSetPreferences.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

from ...lsp.requestMessage import RequestMessage


class Method(Enum):
    keith_preferences_setPreferences = 'keith/preferences/setPreferences'


class Params(BaseModel):
    diagram_shouldSelectDiagram: bool = Field(..., alias='diagram.shouldSelectDiagram')
    diagram_shouldSelectText: bool = Field(..., alias='diagram.shouldSelectText')
    diagram_incrementalDiagramGenerator: bool = Field(
        ..., alias='diagram.incrementalDiagramGenerator'
    )
    diagram_clientLayout: bool | None = Field(None, alias='diagram.clientLayout')


class KeithPreferencesSetpreferences(RequestMessage):
    method: Method | None = 'keith/preferences/setPreferences'
    params: Params
