# generated by datamodel-codegen:
#   filename:  sprotty/diagramAccept.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel

from ..lsp.requestMessage import RequestMessage
from .actions import action as action_1


class Method(Enum):
    diagram_accept = 'diagram/accept'


class ClientId(Enum):
    sprotty = 'sprotty'


class Params(BaseModel):
    clientId: ClientId
    action: action_1.Action


class DiagramAccept(RequestMessage):
    method: Method | None = 'diagram/accept'
    params: Params
