# generated by datamodel-codegen:
#   filename:  klighd/KlighdProperties.json
#   timestamp: 2026-03-02T15:36:09+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from . import SKGraphSchema


class Property(BaseModel):
    id: str
    defaultValue: Any


class IsNodeTitle(Property):
    id: str | None = 'klighd.isNodeTitle'
    defaultValue: bool | None = True


class Tooltip(Property):
    id: str | None = 'klighd.tooltip'
    defaultValue: str | None = ''


class ProxyViewRenderNodeAsProxy(Property):
    id: str | None = 'de.cau.cs.kieler.klighd.proxyView.renderNodeAsProxy'
    defaultValue: bool | None = True


class SemanticFilterTag(BaseModel):
    tag: str | None = None
    num: float | None = 0


class RenderingId(Property):
    id: str | None = 'klighd.lsp.rendering.id'
    defaultValue: str | None = ''


class ProxyViewProxyRendering(Property):
    id: str | None = 'de.cau.cs.kieler.klighd.proxyView.proxyRendering'
    defaultValue: list[SKGraphSchema.KGraphData] | None = Field(default_factory=list)


class SemanticFilterTags(Property):
    id: str | None = 'de.cau.cs.kieler.klighd.semanticFilter.tags'
    defaultValue: list[SemanticFilterTag] | None = Field(default_factory=list)
