# generated by datamodel-codegen:
#   filename:  klighd/SKGraphSchema.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class SModelElement(BaseModel):
    type: str
    id: str
    children: list[SModelElement] | None = Field(default_factory=list)
    trace: str | None = None


class Size(BaseModel):
    width: float | None = None
    height: float | None = None


class Position(BaseModel):
    x: float | None = None
    y: float | None = None


class SShapeElement(SModelElement):
    size: Size | None = Field(
        default_factory=lambda: Size.parse_obj({'width': 0.0, 'height': 0.0})
    )
    position: Position | None = Field(
        default_factory=lambda: Position.parse_obj({'x': 0.0, 'y': 0.0})
    )


class JunctionPoint(BaseModel):
    x: float | None = None
    y: float | None = None


class KGraphData(BaseModel):
    properties: dict[str, Any] | None = {}


class KPlacementData(BaseModel):
    type: str | None = 'KPlacementDataImpl'


class KGridPlacementData(KPlacementData):
    minCellWidth: float | None = 0
    minCellHeight: float | None = 0
    flexibleWidth: bool | None = True
    flexibleHeight: bool | None = True
    type: str | None = 'KGridPlacementDataImpl'


class KXPosition(BaseModel):
    absolute: float | None = None
    relative: float | None = None
    type: str | None = 'KXPositionImpl'


class KYPosition(BaseModel):
    absolute: float | None = None
    relative: float | None = None
    type: str | None = 'KYPositionImpl'


class KLeftPosition(KXPosition):
    type: str | None = 'KLeftPositionImpl'


class KRightPosition(KXPosition):
    type: str | None = 'KRightPositionImpl'


class KTopPosition(KYPosition):
    type: str | None = 'KTopPositionImpl'


class KBottomPosition(KYPosition):
    type: str | None = 'KBottomPositionImpl'


class KPlacement(BaseModel):
    type: str | None = 'KPlacementImpl'


class KStyle(BaseModel):
    propagateToChildren: bool | None = False
    modifierId: str | None = None
    selection: bool | None = False
    type: str | None = 'KStyleImpl'


class KColor(BaseModel):
    red: float | None = 0
    green: float | None = 0
    blue: float | None = 0


class KInvisibility(KStyle):
    invisible: bool | None = True
    type: str | None = 'KInvisibilityImpl'


class Trigger(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class TriggerSingleClick(Enum):
    number_0 = 0


class ModifierState(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2


class ModifierStateDontCare(Enum):
    number_0 = 0


class SKElement(BaseModel):
    data: list[KGraphData] | None = Field(default_factory=list)
    properties: dict[str, Any] | None = {}
    type: str


class SKGraph(SKElement, SModelElement):
    type: str | None = 'graph'
    revision: float
    children: list[SModelElement] | None = Field(
        default_factory=list, max_items=1, min_items=1
    )


class SKNode(SKElement, SShapeElement):
    type: str | None = 'node'


class SKLabel(SKElement, SModelElement):
    text: str
    type: str | None = 'label'


class SKEdge(SKElement, SModelElement):
    sourceId: str
    targetId: str
    junctionPoints: list[JunctionPoint] | None = Field(default_factory=list)
    type: str | None = 'edge'


class SKPort(SKElement, SShapeElement):
    type: str | None = 'port'


class KPosition(BaseModel):
    x: KXPosition | None = None
    y: KYPosition | None = None
    type: str | None = 'KPositionImpl'


class KGridPlacement(KPlacement):
    numColumns: float | None = 0
    topLeft: KPosition | None = None
    bottomRight: KPosition | None = None
    type: str | None = 'KGridPlacementImpl'


class KColoringImpl(KStyle):
    color: KColor | None = None
    alpha: float | None = 255
    targetColor: KColor | None = None
    targetAlpha: float | None = 0
    gradientAngle: float | None = 0


class KAction(BaseModel):
    actionId: str | None = None
    trigger: Trigger | None = None
    altPressed: ModifierState | None = None
    ctrlCmdPressed: ModifierState | None = None
    shiftPressed: ModifierState | None = None
    type: str | None = 'KActionImpl'


class KRendering(KGraphData):
    placementData: KPlacementData | None = None
    styles: list[KStyle] | None = Field(default_factory=list)
    actions: list[KAction] | None = Field(default_factory=list)
    type: str | None = 'KRenderingImpl'


class KContainerRendering(KRendering):
    children: list[KRendering] | None = Field(default_factory=list)
    childPlacement: KPlacement | None = None
    type: str | None = 'KContainerRenderingImpl'


class KRectangle(KContainerRendering):
    type: str | None = 'KRectangleImpl'


class KRoundedRectangle(KRectangle):
    cornerWidth: float | None = None
    cornerHeight: float | None = None
    type: str | None = 'KRoundedRectangleImpl'


class KPolyline(KContainerRendering):
    type: str | None = 'KPolylineImpl'
    junctionPointRendering: KRendering | None = None


class KPolygon(KPolyline):
    type: str | None = 'KPolygonImpl'


class KSpline(KPolyline):
    type: str | None = 'KSplineImpl'


class KImage(KContainerRendering):
    bundleName: str | None = None
    imagePath: str | None = None
    type: str | None = 'KImageImpl'


class KEllipse(KContainerRendering):
    type: str | None = 'KEllipseImpl'


class KArc(KContainerRendering):
    startAngle: float | None = None
    arcAngle: float | None = None
    type: str | None = 'KArcImpl'


class KText(KContainerRendering):
    text: str | None = None
    clip: bool | None = None
    type: str | None = 'KTextImpl'


class KPointPlacementData(KPlacementData):
    referencePoint: KPosition | None = None
    horizontalAlignment: float | None = 0
    verticalAlignment: float | None = 0
    horizontalMargin: float | None = 0
    verticalMargin: float | None = 0
    minWidth: float | None = 0
    minHeight: float | None = 0
    type: str | None = 'KPointPlacementDataImpl'


class KAreaPlacementData(KPlacementData):
    topLeft: KPosition | None = None
    bottomRight: KPosition | None = None
    type: str | None = 'KAreaPlacementDataImpl'


SModelElement.update_forward_refs()
