# generated by datamodel-codegen:
#   filename:  klighd/SynthesisOptionSchema.json
#   timestamp: 2026-02-24T10:26:14+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel


class SynthesisOptionSchema(BaseModel):
    pass


class Type(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4
    number_5 = 5


class Type1(Enum):
    number_0 = 0


class Type2(Enum):
    number_1 = 1


class Type3(Enum):
    number_2 = 2


class Range(BaseModel):
    first: float | None = None
    second: float | None = None


class Type4(Enum):
    number_3 = 3


class Type5(Enum):
    number_4 = 4


class Type6(Enum):
    number_5 = 5


class ValuedSynthesisOption(BaseModel):
    synthesisOption: (
        CheckSynthesisOption
        | ChoiceSynthesisOption
        | RangeSynthesisOption
        | TextSynthesisOption
        | SeparatorSynthesisOption
        | CategorySynthesisOption
    )
    currentValue: str | float | bool


class SynthesisOption(BaseModel):
    id: str
    name: str
    type: Type
    updateAction: str | None = None
    category: CategorySynthesisOption | None = None
    sourceHash: str
    initialValue: Any


class CheckSynthesisOption(SynthesisOption):
    type: Type1 | None = 0
    initialValue: bool | None = None


class ChoiceSynthesisOption(SynthesisOption):
    type: Type2 | None = 1
    initialValue: str | None = None
    values: list[str]


class RangeSynthesisOption(SynthesisOption):
    type: Type3 | None = 2
    initialValue: float | None = None
    range: Range
    stepSize: float


class TextSynthesisOption(SynthesisOption):
    type: Type4 | None = 3
    initialValue: str | None = None


class SeparatorSynthesisOption(SynthesisOption):
    type: Type5 | None = 4


class CategorySynthesisOption(SynthesisOption):
    type: Type6 | None = 5
    initialValue: bool | None = None


ValuedSynthesisOption.update_forward_refs()
SynthesisOption.update_forward_refs()
CheckSynthesisOption.update_forward_refs()
ChoiceSynthesisOption.update_forward_refs()
RangeSynthesisOption.update_forward_refs()
TextSynthesisOption.update_forward_refs()
SeparatorSynthesisOption.update_forward_refs()
CategorySynthesisOption.update_forward_refs()
